---
- name: Basic System Setup
  hosts: localhost
  become: yes  

  tasks:
    - name: Ensure apt cache is updated
      apt:
        update_cache: yes

    - name: Install git
      apt:
        name: git
        state: present

    - name: Install curl
      apt:
        name: curl
        state: present

    - name: Install vim
      apt:
        name: vim
        state: present

    - name: Ensure system is up to date
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 3600  
